# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev48+g577155c.d20230709'
__version_tuple__ = version_tuple = (0, 1, 'dev48', 'g577155c.d20230709')
