name: Package

on:
  - push

jobs:
  build_source_dist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v4.0.0
          with:
            python-version: "3.11"

        - name: Install build
          run: |
            python -m pip install --upgrade pip
            pip install build setuptools wheel twine

        - name: Run build
          run: python -m build

        - uses: actions/upload-artifact@v4
          with:
            path: ./dist/*

  publish:
    name: Publish package
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs:
      - build_source_dist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}